export type RuntimeConfig = { base_url: string; api_key: string; model_id: string; api_protocol: '' | 'anthropic-messages' | 'openai-completions' | 'openai-responses'; thinking_level: 'off' | 'minimal' | 'low' | 'medium' | 'high' }
export type StoredRuntimeConfig = Omit<RuntimeConfig, 'api_key'> & { has_api_key: boolean; credential_error?: string }
export type ModelConnectionStatus = 'unverified' | 'testing' | 'connected' | 'failed'
export type Artifact = { path: string; kind: string; fingerprint: string; size: number; status: string; details: { violations?: string[] } }
export type PendingRequest = { request_id: string; kind: 'user_input'; payload: Record<string, unknown>; state: string }
export type ConversationSourceType = 'opencode' | 'claude-code' | 'codex'
export type ConversationSource = { path: string; source_type: ConversationSourceType; authorization: 'task3_parse'; state: 'authorized'; size: number; created_at?: string }
export type SessionMode = 'live' | 'history'
export type Session = { id: string; project: string; title: string; state: string; mode: SessionMode; can_send: boolean; analysis_started?: boolean; runtime_connected?: boolean; error_code?: string | null; error_message?: string | null; created_at: string; updated_at: string; pending_requests?: PendingRequest[]; artifacts?: Artifact[]; conversation_sources?: ConversationSource[] }
export type UIEvent = { session_id: string; sequence: number; created_at: string; type: string; payload: Record<string, unknown> }
export type SessionSnapshot = { session: Session; events: UIEvent[]; artifacts: Artifact[]; pending_requests: PendingRequest[] }
export type EvidenceReadback = { citation_id: string; source: string; record: Record<string, unknown>; readback: string }
